name: GitHub Actions Demo #工作流

on: [push] # 触发条件
permissions: # 权限配置
  contents: write

jobs: # 任务
  build-and-deploy: # 任务名称
    runs-on: ubuntu-latest # 运行环境
    steps: # 步骤
      - name: Checkout # 检出代码
        uses: actions/checkout@v6 # 检出代码操作

      - name: install and build
        run: |
          npm install pnpm -g 
          pnpm install 
          pnpm docs:build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4 # 部署操作
        with:
          folder: docs/.vitepress/dist # 部署的文件夹
